### ISSUE TITLE
Cluster is degraded banner will not go away in On-Prem testing environment with less than 5 machines

### ISSUE THREAD

**Issue by rommeltrejo** [microsoft/service-fabric-explorer#241]
After upgrading to 6.5.676.9590 the new banner appears as an error on the Main Pages. 
There is no way to disable this and the [link ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-capacity#the-reliability-characteristics-of-the-cluster) takes you to a page designed for users using Azure Web services.
Error:
 Cluster is degraded because it does not have 5 seed nodes. See link for more details (link)

**Comment by jeffj6123** [comment]
Hello,
With the latest CU released for 6.5 this message was added to point out when running on an unsupported scenario for production workloads on Azure as defined here, https://aka.ms/servicefabric/reliability

The wording and appearance of this message have been misleading and overly alarming and will be changed with 7.0 to be much more clear about it referring to production workload supportability and also being removable instead of a persisted red banner. Additionally it will only show on SFRP clusters.

NOTE: This banner doesn’t reflect the actual cluster health and was meant to be regarded as a recommendation to increase the reliability if the cluster was meant for production workloads.

Sorry for any confusion this banner has created.

**Comment by rommeltrejo** [comment]
Issue was fixed.
