### ISSUE TITLE
Expand/Collapse links are inverted

### ISSUE THREAD

**Issue by javierdpt** [microsoft/service-fabric-explorer#318]
Hi SF team, I think this new version is really good. I noticed the expand and collapse are inverted it should be when contracted ▼ and when expanded ▲. Hope this helps, I kind of noticed is on purpose to use the same icon "▼" you have in the old version but for me should be the other way around just to follow existing conventions. Is a minor thing and It can stay that way, you can close this issue, is not a deal breaker but I noticed and I wanted to give you guys my feedback.

**Comment by jeffj6123** [comment]
Hey, @javierdpt you are referring to the tree navigation right? I do agree that those should be flipped because it does go against convention. Right now it is following the previous versions, but this might be the best opportunity to flip them without people really thinking about it. Good thing to point out.
